version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gfi_backend
    env_file: .env
    #volumes:
    #  - app/:/app:cached
    depends_on:
      - db
    networks:
      - gfi
  db:
    image: postgres:12-alpine
    container_name: gfi_database
    env_file: .env
    networks:
      - gfi

networks:
  gfi:
