version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gfi_backend
    entrypoint: sh start.sh
    ports:
      - "8000:8000"
    tty: true
    env_file: .env
    volumes:
      - .:/gfi:cached
    depends_on:
      - db
    networks:
      - gfi
  db:
    image: postgres:12-alpine
    container_name: gfi_database
    env_file: .env
    networks:
      - gfi

networks:
  gfi:
